### PR TITLE
Feature/milestone 3

### PR DESCRIPTION
**Pull request by oxenprogrammer**
## What does this PR do?
Completes milestone-3 by;
- Making the BooksForm component stateful.
- Connecting the REMOVE_BOOK action to the BookList.
- Updating other Components accordingly.

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle:
Hi @oxenprogrammer! Well done so far! :+1:  There are just a few details for you to work on to complete this milestone. These include:
- [x] Add the `Remove Book` button as part of the `Book` component since the `handleRemoveBook` function is expected to be passed down as a prop to the `Book`. ([screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone3/ImplementsRemoveBook.png))
- [x] __[Optional]__ I've noticed that you've done a lot with styling your app. However, I'd like to remind you that this project has specific styling requirements(milestone 5) which will require you to change your current styling. :bulb: I suggest that you focus on the milestone's requirements for now to avoid double work.

_Please make the necessary changes and submit another code review request._
__[Treasure Kabareebe](https://trekab.github.io)__

**Comment by oxenprogrammer** [comment]
> ### Changes Required! 
> Hi @oxenprogrammer! Well done so far!  There are just a few details for you to work on to complete this milestone. These include:
> 
> * [x]  Add the `Remove Book` button as part of the `Book` component since the `handleRemoveBook` function is expected to be passed down as a prop to the `Book`. ([screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone3/ImplementsRemoveBook.png))
> * [x]  **[Optional]** I've noticed that you've done a lot with styling your app. However, I'd like to remind you that this project has specific styling requirements(milestone 5) which will require you to change your current styling. bulb I suggest that you focus on the milestone's requirements for now to avoid double work.
> 
> _Please make the necessary changes and submit another code review request._
> **[Treasure Kabareebe](https://trekab.github.io)**

@trekab, since I was using a popup, I had passed it inside it as you can see. However, I think I was over engineering it.

**Comment by trekab** [comment]
I understand @oxenprogrammer. I like the pop-up BTW! :+1: It's just that it would be better if you looked into these additional features after you have met the basic project requirements. Otherwise, you might easily conflict with the requirements. :bulb:

**Comment by rukundoeric** [comment]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - Follows gitwork-flow.  💯
  - Codebase looks clean and professional. 💯 
  

- ### To Improve
  - N/A

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/),
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

**Pull request merged**
